plugins {
    id 'com.android.application'
}

android {
    namespace 'com.otakuhoarder.mushokufoldroxy'
    compileSdk 36

    defaultConfig {
        applicationId 'com.otakuhoarder.mushokufoldroxy'
        minSdk 28
        targetSdk 36
        versionCode 8
        versionName '0.7.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
